package org.bgdnstc;

public enum Symbol {
    TYPE_INT, TYPE_FLOAT, TYPE_STRING, SOCKET, UDP_SERVER, UDP_CLIENT,
    INT, FLOAT, STRING,
    EQUALS, ADD, SUB, MUL, DIV, LOOP, WHILE, PRINT,
    RECEIVE, SEND,
    DOT, L_BRACKET, R_BRACKET, L_PARENTHESIS, R_PARENTHESIS, AT,
    IDENTIFIER,
    EOL, EOF
}
